version: '3.8'

services:
  tvm-sdk:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tvm-sdk-dev
    volumes:
      - .:/workspace
      - tvm-cache:/root/.cache
    environment:
      - TVM_VERSION=0.22.0
    working_dir: /workspace
    stdin_open: true
    tty: true
    command: /bin/bash

volumes:
  tvm-cache:
