version: '3.8'

services:
  tvm-sdk:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tvm-sdk-dev
    volumes:
      - .:/workspace
      - pip-cache:/root/.cache/pip
    environment:
      - TVM_VERSION=0.22.0
      - LLVM_CONFIG=/usr/bin/llvm-config
    working_dir: /workspace
    stdin_open: true
    tty: true

volumes:
  pip-cache:
